//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string DefaultFontName {
            get {
                return ((string)(this["DefaultFontName"]));
            }
            set {
                this["DefaultFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float DefaultFontSize {
            get {
                return ((float)(this["DefaultFontSize"]));
            }
            set {
                this["DefaultFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFontIsBold {
            get {
                return ((bool)(this["DefaultFontIsBold"]));
            }
            set {
                this["DefaultFontIsBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFontIsItalic {
            get {
                return ((bool)(this["DefaultFontIsItalic"]));
            }
            set {
                this["DefaultFontIsItalic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFontIsUnderline {
            get {
                return ((bool)(this["DefaultFontIsUnderline"]));
            }
            set {
                this["DefaultFontIsUnderline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultFontIsStrikeout {
            get {
                return ((bool)(this["DefaultFontIsStrikeout"]));
            }
            set {
                this["DefaultFontIsStrikeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public int AutoSaveTime {
            get {
                return ((int)(this["AutoSaveTime"]));
            }
            set {
                this["AutoSaveTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Office2007Blue")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public string ThemeColor {
            get {
                return ((string)(this["ThemeColor"]));
            }
            set {
                this["ThemeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseSystemTitleBar {
            get {
                return ((bool)(this["IsUseSystemTitleBar"]));
            }
            set {
                this["IsUseSystemTitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowDeleteWarningTaskDialog {
            get {
                return ((bool)(this["IsShowDeleteWarningTaskDialog"]));
            }
            set {
                this["IsShowDeleteWarningTaskDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseAutoSave {
            get {
                return ((bool)(this["IsUseAutoSave"]));
            }
            set {
                this["IsUseAutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DefaultRTBZoomFactor_FloatType {
            get {
                return ((float)(this["DefaultRTBZoomFactor_FloatType"]));
            }
            set {
                this["DefaultRTBZoomFactor_FloatType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultRTBZoomFactor_IntType {
            get {
                return ((int)(this["DefaultRTBZoomFactor_IntType"]));
            }
            set {
                this["DefaultRTBZoomFactor_IntType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseAutoWordSelection {
            get {
                return ((bool)(this["IsUseAutoWordSelection"]));
            }
            set {
                this["IsUseAutoWordSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseWordWarp {
            get {
                return ((bool)(this["IsUseWordWarp"]));
            }
            set {
                this["IsUseWordWarp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowStatusBar {
            get {
                return ((bool)(this["IsShowStatusBar"]));
            }
            set {
                this["IsShowStatusBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MiniToolBar")]
        public string MiniToolBarOrRadialMenu {
            get {
                return ((string)(this["MiniToolBarOrRadialMenu"]));
            }
            set {
                this["MiniToolBarOrRadialMenu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleGeminiAPIKey {
            get {
                return ((string)(this["GoogleGeminiAPIKey"]));
            }
            set {
                this["GoogleGeminiAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleOCRAPIKey {
            get {
                return ((string)(this["GoogleOCRAPIKey"]));
            }
            set {
                this["GoogleOCRAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleMapsAPIKey {
            get {
                return ((string)(this["GoogleMapsAPIKey"]));
            }
            set {
                this["GoogleMapsAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenAIChatGPTAPIKey {
            get {
                return ((string)(this["OpenAIChatGPTAPIKey"]));
            }
            set {
                this["OpenAIChatGPTAPIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOptimizedTachModeRibbon {
            get {
                return ((bool)(this["IsOptimizedTachModeRibbon"]));
            }
            set {
                this["IsOptimizedTachModeRibbon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppStartupTaskMode {
            get {
                return ((int)(this["AppStartupTaskMode"]));
            }
            set {
                this["AppStartupTaskMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DefaultFontTextColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultFontTextColor"]));
            }
            set {
                this["DefaultFontTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultFontTextHilightColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultFontTextHilightColor"]));
            }
            set {
                this["DefaultFontTextHilightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsShowSelectionMargin {
            get {
                return ((bool)(this["IsShowSelectionMargin"]));
            }
            set {
                this["IsShowSelectionMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsUseAIFunction {
            get {
                return ((bool)(this["IsUseAIFunction"]));
            }
            set {
                this["IsUseAIFunction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSaveMode {
            get {
                return ((int)(this["DefaultSaveMode"]));
            }
            set {
                this["DefaultSaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDocsCloseOnSave {
            get {
                return ((bool)(this["IsDocsCloseOnSave"]));
            }
            set {
                this["IsDocsCloseOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMinimizedRibbon {
            get {
                return ((bool)(this["IsMinimizedRibbon"]));
            }
            set {
                this["IsMinimizedRibbon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT1Visible {
            get {
                return ((bool)(this["QAT1Visible"]));
            }
            set {
                this["QAT1Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT2Visible {
            get {
                return ((bool)(this["QAT2Visible"]));
            }
            set {
                this["QAT2Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT3Visible {
            get {
                return ((bool)(this["QAT3Visible"]));
            }
            set {
                this["QAT3Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT4Visible {
            get {
                return ((bool)(this["QAT4Visible"]));
            }
            set {
                this["QAT4Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT5Visible {
            get {
                return ((bool)(this["QAT5Visible"]));
            }
            set {
                this["QAT5Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT6Visible {
            get {
                return ((bool)(this["QAT6Visible"]));
            }
            set {
                this["QAT6Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT7Visible {
            get {
                return ((bool)(this["QAT7Visible"]));
            }
            set {
                this["QAT7Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QAT8Visible {
            get {
                return ((bool)(this["QAT8Visible"]));
            }
            set {
                this["QAT8Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Theme_IntType {
            get {
                return ((int)(this["Theme_IntType"]));
            }
            set {
                this["Theme_IntType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseOffice2007RibbonShape {
            get {
                return ((bool)(this["IsUseOffice2007RibbonShape"]));
            }
            set {
                this["IsUseOffice2007RibbonShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseDialogAndMdiWindowOnSystemTitleBar {
            get {
                return ((bool)(this["IsUseDialogAndMdiWindowOnSystemTitleBar"]));
            }
            set {
                this["IsUseDialogAndMdiWindowOnSystemTitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentDocsPath {
            get {
                return ((string)(this["RecentDocsPath"]));
            }
            set {
                this["RecentDocsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseRichTextBoxDarkMode {
            get {
                return ((bool)(this["IsUseRichTextBoxDarkMode"]));
            }
            set {
                this["IsUseRichTextBoxDarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUseDarkModeTitleBar {
            get {
                return ((bool)(this["IsUseDarkModeTitleBar"]));
            }
            set {
                this["IsUseDarkModeTitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QATLoaction {
            get {
                return ((int)(this["QATLoaction"]));
            }
            set {
                this["QATLoaction"] = value;
            }
        }
    }
}
