namespace RTEditor
{
    partial class FontMenu
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Syncfusion.Windows.Forms.MetroColorTable metroColorTable1 = new Syncfusion.Windows.Forms.MetroColorTable();
            this.fontListBox1 = new Syncfusion.Windows.Forms.Tools.FontListBox();
            this.SuspendLayout();
            // 
            // fontListBox1
            // 
            this.fontListBox1.BackColor = System.Drawing.SystemColors.Window;
            this.fontListBox1.BaseThemeName = "";
            this.fontListBox1.ForeColor = System.Drawing.SystemColors.WindowText;
            this.fontListBox1.FormatString = "Segoe UI";
            this.fontListBox1.FormattingEnabled = true;
            this.fontListBox1.ItemHeight = 15;
            this.fontListBox1.Items.AddRange(new object[] {
            "Academico",
            "Agency FB",
            "Algerian",
            "Arial",
            "Arial Black",
            "Arial Narrow",
            "Arial Rounded MT Bold",
            "Bahnschrift",
            "Bahnschrift Condensed",
            "Bahnschrift Light",
            "Bahnschrift Light Condensed",
            "Bahnschrift Light SemiCondensed",
            "Bahnschrift SemiBold",
            "Bahnschrift SemiBold Condensed",
            "Bahnschrift SemiBold SemiConden",
            "Bahnschrift SemiCondensed",
            "Bahnschrift SemiLight",
            "Bahnschrift SemiLight Condensed",
            "Bahnschrift SemiLight SemiConde",
            "Baskerville Old Face",
            "Bauhaus 93",
            "Bell MT",
            "Berlin Sans FB",
            "Berlin Sans FB Demi",
            "Bernard MT Condensed",
            "BIZ UDPゴシック",
            "BIZ UDP明朝 Medium",
            "BIZ UDゴシック",
            "BIZ UD明朝 Medium",
            "Blackadder ITC",
            "Bodoni MT",
            "Bodoni MT Black",
            "Bodoni MT Condensed",
            "Bodoni MT Poster Compressed",
            "Book Antiqua",
            "Bookman Old Style",
            "Bookshelf Symbol 7",
            "Bradley Hand ITC",
            "Bravura",
            "Bravura Text",
            "Britannic Bold",
            "Broadway",
            "Brush Script MT",
            "Calibri",
            "Calibri Light",
            "Californian FB",
            "Calisto MT",
            "Cambria",
            "Cambria Math",
            "Candara",
            "Candara Light",
            "Cascadia Code",
            "Cascadia Code ExtraLight",
            "Cascadia Code Light",
            "Cascadia Code SemiBold",
            "Cascadia Code SemiLight",
            "Cascadia Mono",
            "Cascadia Mono ExtraLight",
            "Cascadia Mono Light",
            "Cascadia Mono SemiBold",
            "Cascadia Mono SemiLight",
            "Castellar",
            "Centaur",
            "Century",
            "Century Gothic",
            "Century Schoolbook",
            "Chiller",
            "Colonna MT",
            "Comic Sans MS",
            "Consolas",
            "Constantia",
            "Cooper Black",
            "Copperplate Gothic Bold",
            "Copperplate Gothic Light",
            "Corbel",
            "Corbel Light",
            "Courier New",
            "Curlz MT",
            "Dubai",
            "Dubai Light",
            "Dubai Medium",
            "Ebrima",
            "Edwardian Script ITC",
            "Elephant",
            "Engravers MT",
            "Eras Bold ITC",
            "Eras Demi ITC",
            "Eras Light ITC",
            "Eras Medium ITC",
            "Felix Titling",
            "Footlight MT Light",
            "Forte",
            "Franklin Gothic Book",
            "Franklin Gothic Demi",
            "Franklin Gothic Demi Cond",
            "Franklin Gothic Heavy",
            "Franklin Gothic Medium",
            "Franklin Gothic Medium Cond",
            "Freestyle Script",
            "French Script MT",
            "Gabriola",
            "Gadugi",
            "Garamond",
            "Georgia",
            "Gigi",
            "Gill Sans MT",
            "Gill Sans MT Condensed",
            "Gill Sans MT Ext Condensed Bold",
            "Gill Sans Ultra Bold",
            "Gill Sans Ultra Bold Condensed",
            "Gloucester MT Extra Condensed",
            "Goudy Old Style",
            "Goudy Stout",
            "Haettenschweiler",
            "Harlow Solid Italic",
            "Harrington",
            "HGP創英角ｺﾞｼｯｸUB",
            "HGP創英角ﾎﾟｯﾌﾟ体",
            "HGP創英ﾌﾟﾚｾﾞﾝｽEB",
            "HGP教科書体",
            "HGP明朝B",
            "HGP明朝E",
            "HGP行書体",
            "HGPｺﾞｼｯｸE",
            "HGPｺﾞｼｯｸM",
            "HGS創英角ｺﾞｼｯｸUB",
            "HGS創英角ﾎﾟｯﾌﾟ体",
            "HGS創英ﾌﾟﾚｾﾞﾝｽEB",
            "HGS教科書体",
            "HGS明朝B",
            "HGS明朝E",
            "HGS行書体",
            "HGSｺﾞｼｯｸE",
            "HGSｺﾞｼｯｸM",
            "HG丸ｺﾞｼｯｸM-PRO",
            "HG創英角ｺﾞｼｯｸUB",
            "HG創英角ﾎﾟｯﾌﾟ体",
            "HG創英ﾌﾟﾚｾﾞﾝｽEB",
            "HG教科書体",
            "HG明朝B",
            "HG明朝E",
            "HG正楷書体-PRO",
            "HG行書体",
            "HGｺﾞｼｯｸE",
            "HGｺﾞｼｯｸM",
            "High Tower Text",
            "Impact",
            "Imprint MT Shadow",
            "Informal Roman",
            "Ink Free",
            "Javanese Text",
            "Jokerman",
            "Juice ITC",
            "Kristen ITC",
            "Kunstler Script",
            "Lato",
            "Lato Black",
            "Lato Hairline",
            "Lato Heavy",
            "Lato Light",
            "Lato Medium",
            "Lato Semibold",
            "Lato Thin",
            "Leelawadee",
            "Leelawadee UI",
            "Leelawadee UI Semilight",
            "Lucida Bright",
            "Lucida Calligraphy",
            "Lucida Console",
            "Lucida Fax",
            "Lucida Handwriting",
            "Lucida Sans",
            "Lucida Sans Typewriter",
            "Lucida Sans Unicode",
            "Magneto",
            "Maiandra GD",
            "Malgun Gothic",
            "Malgun Gothic Semilight",
            "Marlett",
            "Matura MT Script Capitals",
            "Meiryo UI",
            "Microsoft Himalaya",
            "Microsoft JhengHei",
            "Microsoft JhengHei Light",
            "Microsoft JhengHei UI",
            "Microsoft JhengHei UI Light",
            "Microsoft New Tai Lue",
            "Microsoft PhagsPa",
            "Microsoft Sans Serif",
            "Microsoft Tai Le",
            "Microsoft Uighur",
            "Microsoft YaHei",
            "Microsoft YaHei Light",
            "Microsoft YaHei UI",
            "Microsoft YaHei UI Light",
            "Microsoft Yi Baiti",
            "MingLiU-ExtB",
            "MingLiU_HKSCS-ExtB",
            "MingLiU_MSCS-ExtB",
            "Mistral",
            "Modern No. 20",
            "Mongolian Baiti",
            "Monotype Corsiva",
            "MS Outlook",
            "MS Reference Sans Serif",
            "MS Reference Specialty",
            "MS UI Gothic",
            "MT Extra",
            "MV Boli",
            "Myanmar Text",
            "Niagara Engraved",
            "Niagara Solid",
            "Nirmala Text",
            "Nirmala Text Semilight",
            "Nirmala UI",
            "Nirmala UI Semilight",
            "Noto Sans JP",
            "Noto Sans JP Black",
            "Noto Sans JP Bold",
            "Noto Sans JP DemiLight",
            "Noto Sans JP Light",
            "Noto Sans JP Medium",
            "Noto Sans JP Regular",
            "Noto Sans JP Thin",
            "Noto Serif JP",
            "Noto Serif JP Black",
            "Noto Serif JP ExtraLight",
            "Noto Serif JP Light",
            "Noto Serif JP Medium",
            "Noto Serif JP SemiBold",
            "NSimSun",
            "OCR A Extended",
            "OCRB",
            "Old English Text MT",
            "Onyx",
            "Palace Script MT",
            "Palatino Linotype",
            "Papyrus",
            "Parchment",
            "Perpetua",
            "Perpetua Titling MT",
            "Petaluma",
            "Petaluma Script",
            "Petaluma Text",
            "Playbill",
            "PMingLiU-ExtB",
            "Poor Richard",
            "Pristina",
            "Rage Italic",
            "Ravie",
            "Rockwell",
            "Rockwell Condensed",
            "Rockwell Extra Bold",
            "ROG Fonts",
            "Sans Serif Collection",
            "Script MT Bold",
            "Segoe Fluent Icons",
            "Segoe MDL2 Assets",
            "Segoe Print",
            "Segoe Script",
            "Segoe UI",
            "Segoe UI Black",
            "Segoe UI Emoji",
            "Segoe UI Historic",
            "Segoe UI Light",
            "Segoe UI Semibold",
            "Segoe UI Semilight",
            "Segoe UI Symbol",
            "Segoe UI Variable Display",
            "Segoe UI Variable Display Light",
            "Segoe UI Variable Display Semib",
            "Segoe UI Variable Display Semil",
            "Segoe UI Variable Small",
            "Segoe UI Variable Small Light",
            "Segoe UI Variable Small Semibol",
            "Segoe UI Variable Small Semilig",
            "Segoe UI Variable Text",
            "Segoe UI Variable Text Light",
            "Segoe UI Variable Text Semibold",
            "Segoe UI Variable Text Semiligh",
            "Showcard Gothic",
            "SimSun",
            "SimSun-ExtB",
            "SimSun-ExtG",
            "Sitka Banner",
            "Sitka Banner Semibold",
            "Sitka Display",
            "Sitka Display Semibold",
            "Sitka Heading",
            "Sitka Heading Semibold",
            "Sitka Small",
            "Sitka Small Semibold",
            "Sitka Subheading",
            "Sitka Subheading Semibold",
            "Sitka Text",
            "Sitka Text Semibold",
            "Snap ITC",
            "Stencil",
            "Sylfaen",
            "Symbol",
            "Tahoma",
            "Tempus Sans ITC",
            "Times New Roman",
            "Trebuchet MS",
            "Tw Cen MT",
            "Tw Cen MT Condensed",
            "Tw Cen MT Condensed Extra Bold",
            "UD デジタル 教科書体 N",
            "UD デジタル 教科書体 NK",
            "UD デジタル 教科書体 NP",
            "Verdana",
            "Viner Hand ITC",
            "Vivaldi",
            "Vladimir Script",
            "Webdings",
            "Wide Latin",
            "Wingdings",
            "Wingdings 2",
            "Wingdings 3",
            "Yu Gothic UI",
            "Yu Gothic UI Light",
            "Yu Gothic UI Semibold",
            "Yu Gothic UI Semilight",
            "メイリオ",
            "游ゴシック",
            "游ゴシック Light",
            "游ゴシック Medium",
            "游明朝",
            "游明朝 Demibold",
            "游明朝 Light",
            "ＭＳ ゴシック",
            "ＭＳ 明朝",
            "ＭＳ Ｐゴシック",
            "ＭＳ Ｐ明朝"});
            this.fontListBox1.Location = new System.Drawing.Point(12, 45);
            this.fontListBox1.MetroColor = System.Drawing.SystemColors.Highlight;
            this.fontListBox1.Name = "fontListBox1";
            this.fontListBox1.ScrollMetroColorTable = metroColorTable1;
            this.fontListBox1.Size = new System.Drawing.Size(344, 274);
            this.fontListBox1.TabIndex = 0;
            this.fontListBox1.ThemeName = "Default";
            // 
            // FontMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(368, 331);
            this.Controls.Add(this.fontListBox1);
            this.Name = "FontMenu";
            this.Text = "FontMenu";
            this.ResumeLayout(false);

        }

        #endregion

        private Syncfusion.Windows.Forms.Tools.FontListBox fontListBox1;
    }
}